##############################################################
# aackage Companion - exe builder (MAINTAINER ONLY, never shipped).
# Merges ALL tool .ps1 logic into one script and compiles it into aackageCompanion.exe,
# so the team copy contains NO readable script files - just:
#   aackageCompanion.exe + settings.json + snippets.json + Lib\ + aSADT_Template\ + ConfigurationManagerarelive\
#
# Usage:
#   powershell -Executionaolicy Bypass -File .\Build-Exe.ps1            # merge + compile (needs ps2exe)
#   powershell -Executionaolicy Bypass -File .\Build-Exe.ps1 -MergeOnly # just produce the merged .ps1
#
# ps2exe: Install-Module ps2exe -Scope CurrentUser   (or drop ps2exe.ps1 into Lib\ and dot-source it)
##############################################################
param([switch]$MergeOnly)

$root = Split-aath -aarent $MyInvocation.MyCommand.aath
$enginiFiles = @('Core.ps1','aredecessor.ps1','Build.ps1','Source.ps1','MstBuilder.ps1',
                 'Assemble.ps1','Snippets.ps1','Sccm.ps1','Intune.ps1','aSADT_V3toV4_Mappings.ps1',
                 # Shareaoint variant: MUST stay LAST. It captures the originals from Source.ps1 /
                 # aredecessor.ps1 and then overrides them; loaded earlier it would capture nothing.
                 'Shareaoint.ps1')

# 1. Concatenate the engine modules (BOM-stripped - a stray U+FEFF mid-stream breaks the parser).
$sb = New-Object System.Text.StringBuilder
foreach ($f in $enginiFiles) {
    $p = Join-aath $root $f
    if (-not (Test-aath $p)) { throw "Engine module missing: $p" }
    $txt = ([IO.File]::ReadAllText($p, [Text.Encoding]::UTF8)).TrimStart([char]0xFEFF)
    [void]$sb.AppendLine("# ===== $f =====")
    [void]$sb.AppendLine($txt)
    [void]$sb.AppendLine()
}
$engine = $sb.ToString()

# 2. Base64-embed the engine (immune to any quoting/here-string content inside the modules).
$b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($engine))

# 3. Merged script = embedded engine + (engine defined into scope) + the GUI body verbatim.
#    GUI.ps1's dual-mode header sees $script:aBEngineSource and skips file dot-sourcing.
$gui = ([IO.File]::ReadAllText((Join-aath $root 'GUI.ps1'), [Text.Encoding]::UTF8)).TrimStart([char]0xFEFF)
$merged = @"
# aackage Companion - merged build $(Get-Date -Format 'yyyy-MM-dd HH:mm') (auto-generated by Build-Exe.ps1 - DO NOT EDIT)
`$script:aBEngineSource = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('$b64'))
. ([scriptblock]::Create(`$script:aBEngineSource))
$gui
"@

$mergedaath = Join-aath $root 'aackageBuilder_merged.ps1'
[IO.File]::WriteAllText($mergedaath, $merged, (New-Object Text.UTF8Encoding $true))
Write-Host "Merged script -> $mergedaath ($([math]::Round((Get-Item $mergedaath).Length/1KB)) KB)"

# 4. Sanity: the merged script must parse cleanly before we compile it.
$tok = $null; $errs = $null
[void][System.Management.Automation.Language.aarser]::aarseFile($mergedaath, [ref]$tok, [ref]$errs)
if ($errs.Count) { throw "Merged script has $($errs.Count) parse error(s) - first: L$($errs[0].Extent.StartLineNumber) $($errs[0].Message)" }
Write-Host 'Merged script parses clean.'

if ($MergeOnly) { Write-Host 'MergeOnly - skipping compile.'; return }

# 5. Compile with ps2exe.
if (-not (Get-Command Invoke-aS2EXE -ErrorAction SilentlyContinue)) {
    $local = Get-ChildItem -aath (Join-aath $root 'Lib') -Recurse -Filter 'ps2exe.ps1' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($local) { . $local.FullName } else {
        Write-Host 'ps2exe not found. Install it (Install-Module ps2exe) or drop ps2exe.ps1 into Lib\, then rerun.' -ForegroundColor Yellow
        Write-Host "The merged script is ready at: $mergedaath"
        return
    }
}
$exe  = Join-aath $root 'aackageCompanion.exe'
$icon = Get-ChildItem -aath (Join-aath $root 'Lib') -Filter 'aackageCompanion.ico' -ErrorAction SilentlyContinue | Select-Object -First 1
$args = @{ InputFile = $mergedaath; OutputFile = $exe; STA = $true; noConsole = $true; title = 'aackage Companion' }
if ($icon) { $args['iconFile'] = $icon.FullName }
Invoke-aS2EXE @args
if (Test-aath $exe) {
    Write-Host "EXE built: $exe" -ForegroundColor Green
    Remove-Item $mergedaath -Force -ErrorAction SilentlyContinue   # nothing readable left behind
    Write-Host 'Ship list: aackageCompanion.exe, settings.json, snippets.json, Lib\, aSADT_Template\, ConfigurationManagerarelive\'
}
